{{- if or .Values.query.secrets .Values.query.secretConfigFiles -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imply.query.fullname" . }}
  labels:
{{ include "imply.labels" . | indent 4 }}
{{- with .Values.query.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- if .Values.query.secrets }}
{{ toYaml .Values.query.secrets | indent 2 }}
{{- end }}
{{- range $path, $val := .Values.query.secretConfigFiles }}
  {{ $path | replace "/" "-" | replace "." "-" }}: |
{{ $val | indent 4 }}
{{- end }}
{{- end }}
