apiVersion: {{ ternary "policy/v1" "policy/v1beta1" ( .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" ) }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
spec:
  selector:
    matchLabels:
      app: {{ template "zookeeper.name" . }}
      release: {{ .Release.Name }}
      component: server
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
