apiVersion: v1
appVersion: 3.7.1
description: Centralized service for maintaining configuration information, naming,
  providing distributed synchronization, and providing group services.
home: https://zookeeper.apache.org/
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
kubeVersion: ^1.10.0-0
name: zookeeper
sources:
- https://github.com/apache/zookeeper
- https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper
version: 3.2.0
