{{- if .Values.peon }}
apiVersion: v1
kind: Secret
metadata:
  name: "peon-config-secrets"
  labels:
{{ include "imply.labels" . | indent 4 }}
data:
{{- range $path, $val := .Values.peon.secretConfigFiles }}
  {{ $path | replace "/" "-" | replace "." "-" }}: |
{{ $val | indent 4 }}
{{- end }}
{{- end }}