{{- if and .Values.deployments.agents (gt (.Values.master.replicaCount | int64) 0) -}}
apiVersion: {{ ternary "policy/v1" "policy/v1beta1" ( .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" ) }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "imply.master.fullname" . }}
  labels:
{{ include "imply.labels" . | indent 4 }}
{{- with .Values.master.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "imply.master.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ toYaml .Values.master.podDisruptionBudget | indent 2 }}
{{- end }}
