{{- if or .Values.master.secrets .Values.master.secretConfigFiles -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "imply.master.fullname" . }}
  labels:
{{ include "imply.labels" . | indent 4 }}
{{- with .Values.master.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- if .Values.master.secrets }}
{{ toYaml .Values.master.secrets | indent 2 }}
{{- end }}
{{- range $path, $val := .Values.master.secretConfigFiles }}
  {{ $path | replace "/" "-" | replace "." "-" }}: |
{{ $val | indent 4 }}
{{- end }}
{{- end }}
