apiVersion: v1
kind: Service
metadata:
  name: {{ include "imply.master.fullname" . }}-headless
  labels:
{{ include "imply.labels" . | indent 4 }}
{{- with .Values.master.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
    - port: 8081
      targetPort: coordinator
      name: tcp-coordinator
    - port: 8281
      targetPort: coordinator-tls
      name: tcp-coordinator-tls
    - port: 8090
      targetPort: overlord
      name: tcp-overlord
    - port: 8290
      targetPort: overlord-tls
      name: tcp-overlord-tls
{{- with .Values.master.headlessService.extraPorts }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "imply.master.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
